host_name: api.fedotov.dev.jivosite.com
api_url: https://lottip.orderbynull.me

services:
  mysql:
    host: 127.0.0.1:3306
    proxy: 127.0.0.1:4040
    tags: [Api, Web20, Chatserver]

  postgresql:
    host: 127.0.0.1:5432
    proxy: 127.0.0.1:4041

  redis:
    host: 127.0.0.1:6379
    proxy: 127.0.0.1:4042
    tags: [Web20]

  rabbitmq:
    host: 127.0.0.1:5672
    proxy: 127.0.0.1:4043
    tags: [Api, Chatserver]
